### ISSUE TITLE
1.26.0 crash

### ISSUE THREAD

**Issue by argoyle** [cloudamqp/terraform-provider-cloudamqp#203]
I get a crash for the following resource:
```
resource "cloudamqp_instance" "default" {
  name              = "test"
  plan              = "lemur"
  region            = "amazon-web-services::eu-west-1"
  rmq_version       = "3.8.8"
  nodes             = null
  no_default_alarms = true
}
```

Output:
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│
│   with cloudamqp_instance.default,
│   on main.tf line 1, in resource "cloudamqp_instance" "default":
│    1: resource "cloudamqp_instance" "default" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-cloudamqp_v1.26.0 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 70 [running]:
github.com/84codes/go-api/api.(*API).PlanTypes(0x1400000ec10, {0x0, 0x0}, {0x14000266e50, 0x5})
	github.com/84codes/go-api@v1.12.0/api/metadata.go:60 +0x3c8
github.com/cloudamqp/terraform-provider-cloudamqp/cloudamqp.resourceInstance.func1({0x1059a69a0?, 0x105902a08?}, {0x1059a69a0?, 0x14000603c80?}, {0x105b443c0?, 0x1400000ec10?})
	github.com/cloudamqp/terraform-provider-cloudamqp/cloudamqp/resource_cloudamqp_instance.go:130 +0x7c
github.com/hashicorp/terraform-plugin-sdk/helper/customdiff.ForceNewIfChange.func1(0x14000506e70?, {0x105b443c0, 0x1400000ec10})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/customdiff/force_new.go:35 +0x160
github.com/hashicorp/terraform-plugin-sdk/helper/customdiff.All.func1(0x14000506cc0?, {0x105b443c0, 0x1400000ec10})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/customdiff/compose.go:48 +0x88
github.com/hashicorp/terraform-plugin-sdk/helper/schema.schemaMap.Diff(0x140008115f0, 0x140002236d0, 0x14000506750, 0x1400010ca80, {0x105b443c0, 0x1400000ec10}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/schema.go:524 +0x2b8
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).simpleDiff(0x1059fbba0?, 0x140002236d0, 0x1400026eb58?, {0x105b443c0?, 0x1400000ec10?})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:366 +0x48
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).SimpleDiff(0x14000585080, 0x14000731930, 0x1059fe000?, 0x14000506660?)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:321 +0x6c
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).PlanResourceChange(0x1400089a7d8, {0x140002aec40?, 0x140002aebd0?}, 0x140002aec40)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:643 +0x540
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x105b11620?, 0x1400089a7d8}, {0x105b571e8, 0x140002357d0}, 0x140002aebd0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3287 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400050c3c0, {0x105b5be40, 0x14000642820}, 0x140003a3200, 0x140004faa80, 0x10624a008, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xbac
google.golang.org/grpc.(*Server).handleStream(0x1400050c3c0, {0x105b5be40, 0x14000642820}, 0x140003a3200, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28c

Error: The terraform-provider-cloudamqp_v1.26.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by tbroden84** [comment]
@argoyle 

Think I found your request in our logs, shows an unauthorized request. Please check so that you use the correct API key https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs#argument-reference. Also a fault in our client library that fails to handle the error response.

Could also recommend removing the RabbitMQ version, not possible to choose when creating a shared subscription plan. 
```hcl
resource "cloudamqp_instance" "default" {
  name              = "test"
  plan              = "lemur"
  region            = "amazon-web-services::eu-west-1"
  no_default_alarms = true
}
```

**Comment by tbroden84** [comment]
In latest version 1.26.0 we changed to validate plan and region with our API backend, instead of using hardcoded values in the provider. This will also allow us to grant team/accounts preview plans without making new releases.

Have started on a fix for the error issue, but will still require a valid API key.

**Comment by argoyle** [comment]
Ok, then we'll have to add a secret. 😊 Thanks for quick response!
