### ISSUE TITLE
Can't import existing instance

### ISSUE THREAD

**Issue by pmichna** [cloudamqp/terraform-provider-cloudamqp#40]
Hi, I'm trying to import an existing instance to Terraform and here is what I get:

```
$ terraform import cloudamqp_instance.instance 00000

cloudamqp_instance.instance: Importing from ID "00000"...
cloudamqp_instance.instance: Import prepared!
  Prepared cloudamqp_instance for import
cloudamqp_instance.instance: Refreshing state... [id=00000]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0:
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: goroutine 11 [running]:
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: github.com/84codes/go-api/api.(*API).UrlInformation(0xc0000c42f8, 0xc00009a8a0, 0x5e, 0x3)
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: 	/Users/tobiasbroden/go/pkg/mod/github.com/84codes/go-api@v1.1.0/api/instance.go:149 +0x4bd
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: github.com/cloudamqp/terraform-provider-cloudamqp/cloudamqp.resourceRead(0xc00012bab0, 0x1c7a5a0, 0xc0000c42f8, 0xc00012bab0, 0x0)
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: 	/Users/tobiasbroden/go/src/github.com/cloudamqp/terraform-provider-cloudamqp/cloudamqp/resource_instance.go:140 +0x359
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004d4300, 0xc00023d1d0, 0x1c7a5a0, 0xc0000c42f8, 0xc0004ce2d8, 0x0, 0x0)
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: 	/Users/tobiasbroden/go/pkg/mod/github.com/hashicorp/terraform@v0.12.19/helper/schema/resource.go:455 +0x119
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0004ce040, 0x1f58e00, 0xc0000adc50, 0xc00023cff0, 0xc0004ce040, 0xc0000adc50, 0xc00044bba8)
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: 	/Users/tobiasbroden/go/pkg/mod/github.com/hashicorp/terraform@v0.12.19/helper/plugin/grpc_provider.go:525 +0x3d7
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0x1c50760, 0xc0004ce040, 0x1f58e00, 0xc0000adc50, 0xc00023cfa0, 0x0, 0x1f58e00, 0xc0000adc50, 0xc000380630, 0x8e)
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: 	/Users/tobiasbroden/go/pkg/mod/github.com/hashicorp/terraform@v0.12.19/internal/tfplugin5/tfplugin5.pb.go:3153 +0x23e
2020-02-14T12:53:10.129+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00009ed80, 0x1f652c0, 0xc00009f080, 0xc000478100, 0xc0000aca80, 0x2761950, 0x0, 0x0, 0x0)
2020-02-14T12:53:10.130+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: 	/Users/tobiasbroden/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:998 +0x470
2020-02-14T12:53:10.130+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: google.golang.org/grpc.(*Server).handleStream(0xc00009ed80, 0x1f652c0, 0xc00009f080, 0xc000478100, 0x0)
2020-02-14T12:53:10.130+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: 	/Users/tobiasbroden/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1278 +0xda6
2020-02-14T12:53:10.130+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00022c000, 0xc00009ed80, 0x1f652c0, 0xc00009f080, 0xc000478100)
2020-02-14T12:53:10.130+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: 	/Users/tobiasbroden/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:717 +0x9f
2020-02-14T12:53:10.130+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-02-14T12:53:10.130+0100 [DEBUG] plugin.terraform-provider-cloudamqp_v1.3.0: 	/Users/tobiasbroden/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:715 +0xa1
2020/02/14 12:53:10 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/02/14 12:53:10 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/02/14 12:53:10 [TRACE] [walkImport] Exiting eval tree: import cloudamqp_instance.instance result
2020/02/14 12:53:10 [TRACE] vertex "import cloudamqp_instance.instance result": visit complete
2020/02/14 12:53:10 [TRACE] vertex "cloudamqp_instance.instance (import id \"00000\")": dynamic subgraph encountered errors
2020/02/14 12:53:10 [TRACE] vertex "cloudamqp_instance.instance (import id \"00000\")": visit complete
2020/02/14 12:53:10 [TRACE] dag/walk: upstream of "provider.cloudamqp (close)" errored, so skipping
2020-02-14T12:53:10.134+0100 [DEBUG] plugin: plugin process exited: path=/Users/pmichna/.terraform.d/plugins/terraform-provider-cloudamqp_v1.3.0 pid=36471 error="exit status 2"
2020-02-14T12:53:10.134+0100 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Terraform code:
```
provider "aws" {
  region = "us-east-1"

  assume_role {
    role_arn = "arn:aws:iam::<REDACTED>:role/TerraformReadOnly"
  }
}

terraform {
  backend "s3" {
    bucket   = "<REDACTED>"
    region   = "us-east-1"
    key      = "cloudamqp-test/terraform.tfstate"
    role_arn = "arn:aws:iam::<REDACTED>:role/TerraformReadOnly"
  }
}

provider "cloudamqp" {
  version = "~> 1.3.0"
  apikey = "<REDACTED>"
}

resource "cloudamqp_instance" "instance" {
  name     = "myapp-production"
  plan     = "bunny"
  region   = "amazon-web-services::us-east-1"
}

```

The complete [crash.log](https://gist.github.com/pmichna/97350bf54914d201e3cb299df3d70c49).

## Additional info:

- terraform 0.12.20
- cloudamqp provider 1.3.0
- I've replaced the real instance id in the logs to `00000` (I've taken it from the URL, e.g. `https://customer.cloudamqp.com/instance/00000/edit`)
- in crash.log there is an api key which I don't recognize - it is not the api key I've set for the CloudAMQP provider (I've replaced it with `redacted-api-key` in the logs)

**Comment by tbroden84** [comment]
Hi, 

Thanks for the extended information and crash log, made the troubleshooting much easier. Found the issue in our go-api module. Was caused by a faulty regex expression. Have updated the go-api and released a patch (v1.1.1).

Furthermore about the api key you found in the debug logging. We have two different api's, the first deals with meta data, second alarms, notifications etc. In order to only use one Terraform provider we redirect all api calls through the first one. So the second api key is still provided due to our default workflow.

**Comment by pmichna** [comment]
Thanks @tbroden84 for quick action! Could you make a new release with updated dependencies?

**Comment by tbroden84** [comment]
@pmichna Done, could you please try again.

**Comment by pmichna** [comment]
@tbroden84 Great, it works! Awesome support! 😎
